server:
  port: 8081
spring:
  dubbo:
    application:
      name: service-provider
    base-package: fun.deepsky.dubbo.springboot.samples
    registry:
      address: localhost
      port: 2181
    protocol: 
      name: dubbo
      serialization: hessian2
    provider:
      retries: 0